/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import classes.Fila;
import classes.Senha;
import classes.Senha;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaChamarSenha extends javax.swing.JFrame {
    private Fila fila;
    private Senha senhaChamada;
    private int tentativas;
    /**
     * Creates new form TelaChamarSenha
     */
    public TelaChamarSenha(Fila fila) {
        this.fila = fila;
        this.tentativas = 0; 
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSenhaChamada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnChamar = new javax.swing.JButton();
        btnChamarNovamente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("CHAMAR SENHA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("TIPO:");

        lblSenhaChamada.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblSenhaChamada.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setText("SENHA:");

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTipo.setText("-");

        btnVoltar.setBackground(new java.awt.Color(153, 255, 153));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVoltar.setText("VOLTAR PARA O MENU");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnChamar.setBackground(new java.awt.Color(153, 255, 153));
        btnChamar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChamar.setText("CHAMAR ");
        btnChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarActionPerformed(evt);
            }
        });

        btnChamarNovamente.setBackground(new java.awt.Color(153, 255, 153));
        btnChamarNovamente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChamarNovamente.setText("CHAMAR NOVAMENTE");
        btnChamarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarNovamenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChamarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenhaChamada)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnChamar)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTipo))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSenhaChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnChamar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChamarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaMenu(fila).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarActionPerformed
         if (!fila.filaPreferencial.isEmpty() || !fila.filaNormal.isEmpty()) {
            chamarProximaSenha();
        } else {
            JOptionPane.showMessageDialog(this, "Não há senhas para chamar!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnChamarActionPerformed

    private void btnChamarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarNovamenteActionPerformed
        chamarNovamente();
    }//GEN-LAST:event_btnChamarNovamenteActionPerformed

    private void chamarProximaSenha() {
        if (!fila.filaPreferencial.isEmpty()) {
            // Se houver senhas preferenciais, remove a primeira
            senhaChamada = fila.filaPreferencial.poll();
            lblTipo.setText("Preferencial");
        } else if (!fila.filaNormal.isEmpty()) {
            // Se não houver senhas preferenciais, verifica a fila normal
            senhaChamada = fila.filaNormal.poll();
            lblTipo.setText("Normal");
        } else {
            // Caso não haja senhas em nenhuma fila
            senhaChamada = null;
            lblTipo.setText("Vazia");
        }

        // Atualiza a tela com o número da senha chamada
        if (senhaChamada != null) {
            lblSenhaChamada.setText(String.valueOf(senhaChamada.getNumero()));
        } else {
            lblSenhaChamada.setText("Vazia");
        }

        // Atualiza o botão de chamar novamente
        tentativas = 0;
        btnChamarNovamente.setEnabled(true);
    }


    private void chamarNovamente() {
        if (senhaChamada != null && tentativas < 3) {
            tentativas++;
            lblSenhaChamada.setText(String.valueOf(senhaChamada.getNumero()));  
        }

        if (tentativas >= 3) {
            btnChamarNovamente.setEnabled(false);  // Bloqueia o botão após 3 tentativas
            fila.moverParaFilaAuxiliar(senhaChamada); // Move a senha para a fila auxiliar
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaChamarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaChamarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaChamarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChamarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Fila fila = new Fila();
                new TelaChamarSenha(fila).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamar;
    private javax.swing.JButton btnChamarNovamente;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblSenhaChamada;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
