/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

public class TelaMenu extends javax.swing.JFrame {
    private final Fila fila; //Instância da fila para armazenar as senhas
    private int contadorNormal; // Contador para gerar número de senhas normais
    private int contadorPreferencial; // Contador para gerar número de senhas preferenciais

    
    public TelaMenu(Fila fila) {
        initComponents();
        this.fila = fila;
        contadorNormal = fila.getUltimaSenhaNormal() + 1; // Inicia o contador normal com o último número da fila
        contadorPreferencial = fila.getUltimaSenhaPreferencial() + 1; // Inicia o contador preferencial com o último número da fila
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSenhaNormal = new javax.swing.JButton();
        btnSenhaPref = new javax.swing.JButton();
        btnChamar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnSenhaNormal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSenhaNormal.setText("GERAR SENHA NORMAL");
        btnSenhaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaNormalActionPerformed(evt);
            }
        });

        btnSenhaPref.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSenhaPref.setText("GERAR SENHA PREFERENCIAL");
        btnSenhaPref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaPrefActionPerformed(evt);
            }
        });

        btnChamar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChamar.setText("CHAMAR SENHA");
        btnChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnListar.setText("LISTAR SENHAS");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnRelatorios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRelatorios.setText("RELATÓRIOS");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSair.setText("SAIR DO PROGRAMA");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("GERENCIADOR DE SENHAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSenhaNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSenhaPref, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnChamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(83, 83, 83)
                .addComponent(btnSenhaNormal)
                .addGap(18, 18, 18)
                .addComponent(btnSenhaPref)
                .addGap(18, 18, 18)
                .addComponent(btnChamar)
                .addGap(18, 18, 18)
                .addComponent(btnListar)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorios)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
        new TelaRelatorio().setVisible(true);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnSenhaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaNormalActionPerformed
        // Gera uma senha normal e cria a tela de geração
        Senha senhaNormal = new Senha(contadorNormal++, "n");
        fila.adicionarSenhaNormal(senhaNormal);
        // Exibe a tela GerarSenha com a senha gerada e também o tipo (normal ou preferencial)
        new TelaGerarSenha(String.valueOf(senhaNormal.getNumero()), "Normal").setVisible(true);
    }//GEN-LAST:event_btnSenhaNormalActionPerformed

    private void btnSenhaPrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaPrefActionPerformed
        // Gera uma senha preferencial e cria a tela de geração
        Senha senhaPref = new Senha(contadorPreferencial++, "p");
        fila.adicionarSenhaPreferencial(senhaPref);
    
        // Exibe a tela GerarSenha com a senha gerada e também o tipo (normal ou preferencial)
        new TelaGerarSenha(String.valueOf(senhaPref.getNumero()), "Preferencial").setVisible(true);
    }//GEN-LAST:event_btnSenhaPrefActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        TelaListarSenhas tela = new TelaListarSenhas(fila);
        tela.setVisible(true);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarActionPerformed
        TelaChamarSenha tela = new TelaChamarSenha(fila);
        tela.setVisible(true);
    
    }//GEN-LAST:event_btnChamarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Fila fila = new Fila();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaMenu(fila).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSenhaNormal;
    private javax.swing.JButton btnSenhaPref;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
